#page title
page_title                                : Chatter                                   # Automatically populates with app name if not set and if iOS app ID is set. Otherwise enter manually.

# App Info
ios_app_id                                : #1234793120                                # Required. Enter iOS app ID to automatically populate name, price and icons (e.g. 718043190).

appstore_link                             :                                           # Automatically populates if not set and if iOS app ID is set. Otherwise enter manually.
playstore_link                            :                                           # Enter Google Play Store URL.
presskit_download_link                    : https://theemergelab.com                                          # Enter a link to downloadable file or (e.g. public Dropbox link to a .zip file). 
                                                                                      # Or upload your press kit file to assets and set path accordingly (e.g. "assets/your_press_kit.zip").

app_icon                                  : assets/appicon.png                      # Automatically populates if not set and if iOS app ID is set.  Otherwise enter path to icon file manually.
app_name                                  : Chatter                                   # Automatically populates if not set and if iOS app ID is set.  Otherwise enter manually.
app_price                                 : Free                                      # Automatically populates if not set and if iOS app ID is set.  Otherwise enter manually.
app_description                           : For people like you, from the people who like you.

enable_smart_app_banner                   : true                                      # Set to true to show a smart app banner at top of page on mobile devices.



# Information About Yourself
your_name                                 : The EMERGE Lab at USC                                
your_link                                 : https://theemergelab.com                     
your_city                                 : Los Angeles                                
email_address                             : michaelyao2017@gmail.com
facebook_username                         :                                           
instagram_username                        : theemergelab
twitter_username                          : theEMERGElab
# github_username                           : chatter-usc
youtube_username                          :



# Feature List                            Edit, add or remove features to be presented.
features                                  :
    
  - title                                 : Complicated Contraceptives, Easily Explained
    description                           : Every birth control has its own drug name, dosage, and warning labels. Chatter sifts through the clutter to give you exactly the information you need.
    fontawesome_icon_name                 : prescription

  - title                                 : We're In This Together
    description                           : Learn what your peers and community members are using to meet their own contraceptive needs.
    fontawesome_icon_name                 : smile

  - title                                 : People First
    description                           : Chat anonymously with birth control users and physicians to get personable feedback on what's right for you.
    fontawesome_icon_name                 : comment-dots

  - title                                 : Integrated with Social Accounts
    description                           : Login with your Facebook or Instagram to pool data from all your friends and contacts.
    fontawesome_icon_name                 : address-book
  
  - title                                 : Accessible Always
    description                           : Birth control shouldn't be difficult. Chatter will always remain ad-free and free-to-use for everyone.
    fontawesome_icon_name                 : ad

  - title                                 : Two-Way Conversations
    description                           : Participate in anonymous discussion forums to learn what your peers think about different contraceptives and offer your own insights.
    fontawesome_icon_name                 : tags

  - title                                 : # Social Links
    description                           : # Easily add social media accounts and contact info in the footer via the _config.yml file. No HTML/CSS needed.
    fontawesome_icon_name                 : # link

  - title                                 : # FontAwesome Support
    description                           : # Pick custom Font Awesome icons for the feature list via the _config.yml file. No HTML/CSS needed.
    fontawesome_icon_name                 : # info-circle

  - title                                 : # New Feature Title
    description                           : # New Feature Description
    fontawesome_icon_name                 : # Enter Font Awesome icon name (e.g. star). Find icons on fontawesome.com/icons.



# Theme Settings
topbar_color                              : "#000000"
topbar_transparency                       : 0.5
topbar_title_color                        : "#ffffff"

cover_image                               : assets/headerimage.png                    # Replace with alternative image path or image URL.
cover_overlay_color                       : "#363b3d"
cover_overlay_transparency                : 0.8

device_color                              : black                                     # Set to: blue, black, yellow, coral or white.

body_background_color                     : "#ffffff"

link_color                                : "#1d63ea"

app_title_color                           : "#ffffff"
app_price_color                           : "#ffffff"
app_description_color                     : "#ffffff"

feature_title_color                       : "#000000"
feature_text_color                        : "#666666"

feature_icons_foreground_color            : "#1d63ea"
feature_icons_background_color            : "#e6e6e6"

social_icons_foreground_color             : "#666666"
social_icons_background_color             : "#e6e6e6"

footer_text_color                         : "#666666"













####################################################
### Jekyll Configuration. No need to touch this. ###
####################################################

# Set the Sass partials directory, as we're using @imports
sass:
  style: :compressed # You might prefer to minify using :compressed

# Exclude these files from your production _site
exclude:
  - LICENSE
  - README.md
  - CNAME

collections:
  pages:
    output: true
    permalink: /:path/

# Markdown rendering
markdown: kramdown
